#!/bin/fish

sudo pacman -S --noconfirm --needed base-devel git fish rustup

# Install rustup toolchain
echo "Installing rustup with its stable toolchain ..."
rustup install stable
rustup default stable

sleep 1

# Install Paru
if which paru
  echo "Paru detected."
else
  echo "Installing paru ..."
  git clone https://aur.archlinux.org/paru.git
  pushd paru
  makepkg -si --noconfirm
  popd
  rm -rf paru
end

sleep 1

echo "Refreshing repositories ..."
paru -Syy --noconfirm
paru -Sy --noconfirm archlinux-keyring

sleep 1

echo "Installing base packages ..."
paru -S --noconfirm --needed \
  base-devel \
  clang \
  curl \
  docker \
  docker-compose \
  docker-machine \
  fd \
  fish \
  fnm-bin \
  git \
  go \
  golangci-lint \
  gtk3 \
  gtk4 \
  jq \
  lf \
  luacheck \
  man \
  neovim \
  pdfjs \
  python-adblock \
  python-pip \
  ripgrep \
  rsync \
  rustup \
  stylua \
  tree \
  unzip \
  xdg-utils \
  xdg-user-dirs \
  vscode

sleep 1

echo "Installing necessary packages ..."
paru -S --noconfirm --needed \
  alacritty \
  btop \
  breeze-snow-cursor-theme \
  calc \
  chromium \
  dunst \
  firefox-developer-edition \
  glfw-wayland \
  grim \
  imagemagick \
  imv \
  papirus-icon-theme \
  polkit-kde-agent \
  qt5-wayland \
  qt6-wayland \
  rofi-lbonn-wayland-git \
  sddm-git \
  sddm-sugar-candy-git \
  slurp \
  starship \
  sway \
  swaybg \
  swayidle \
  swaylock-effects-git \
  ttf-roboto \
  waybar \
  wf-recorder \
  wlr-randr \
  wlsunset \
  wl-clipboard \
  xorg-xwayland \
  xorg-xlsclients \
  zathura \
  zathura-pdf-poppler

sleep 1

# Enable systemd services
echo "Enabling services ..."
sudo systemctl enable sddm.service

# SDDM
echo "Configuring SDDM.."
sudo rsync --recursive ./extras/sddm.conf.d /etc/
sudo rsync ./.config/sugar-candy/theme.conf /usr/share/sddm/themes/sugar-candy/

sleep 1

echo "Create default user directories..."
xdg-user-dirs-update

sleep 1
echo "Installing executables ..."
mkdir -p ~/.local/bin
cp ./bin/* ~/.local/bin

sleep 1

# Fonts
echo "Downloading & copying fonts to directories ..."
rm -rf ~/.local/share/{themes,fonts}
mkdir -p ~/.local/share/{themes,fonts}
git clone https://github.com/dangminhngo/fonts.git
cp fonts/Devka/patched/* ~/.local/share/fonts/
cp fonts/Others/* ~/.local/share/fonts/
rm -rf fonts
fc-cache -r

# Run Docker with current user privileges
sudo usermod -aG docker $USER

sleep 1

echo "Copying configuration files to their locations ..."
rm -rf ~/.config
rsync --recursive ./.config ~/

rsync ./extras/.gitconfig ~/
sudo rsync --recursive ./extras/reflector /etc/xdg/

# Install GTK themes
echo "Downloading & copying darkoma GTK themes"
git clone https://github.com/dangminhngo/darkoma.gtk.git
cp -R darkoma.gtk/themes/* ~/.local/share/themes/
rm -rf darkoma.gtk

sleep 1

# Set greeting wallpaper
echo "Setting wallpapers ..."
mkdir -p ~/.config/wallpapers
rsync ./wallpapers/{wallpaper.jpg,lockscreen.jpg} ~/.config/wallpapers/
sudo rsync ./wallpapers/greeting.jpg /usr/share/sddm/themes/sugar-candy/

# Install node
echo "Install Node v18 ..."
fnm install v18

# Remove build dependencies
echo "Removing build dependencies ..."
set i3_installed (paru -Qs i3-wm | grep "local/")
if test -n "$i3_installed"
  paru -Rns --noconfirm i3-wm
end

sleep 1

paru -Rns --noconfirm (paru -Qdtq)

sleep 1

echo "[DONE] Reboot and Enjoy. Happy Coding!"
